# Generated by Django 5.0.4 on 2024-04-16 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategoriya')),
                ('photo', models.ImageField(upload_to='img/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Retsept nomi')),
                ('content', models.TextField(verbose_name='Matni')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Rasmi')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('published', models.BooleanField(default=True, verbose_name='Saytga chiqarish')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='food.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
                'ordering': ['-created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Izoh muallifi')),
                ('text', models.TextField(verbose_name='Izoh')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.recipes', verbose_name='Retsept')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('addres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefon raqam')),
                ('chrome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sayt')),
                ('instagram', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
