# Generated by Django 5.0.4 on 2024-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='addres',
            field=models.CharField(blank=True, default='Uzbekistan', max_length=100, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chrome',
            field=models.CharField(blank=True, default='https://example.com', max_length=150, null=True, verbose_name='Sayt'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, default='https://facebook.com', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, default='https://instagram.com', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='+998 (XX) XXX-XX-XX', max_length=14, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
